name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1.1.0
      - name: Install libsqlite3-mod-spatialite
        run: sudo apt-get install libsqlite3-mod-spatialite
      - name: Install GDAL library
        run: sudo apt-get install gdal-bin
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.linux.test.txt
      - name: Migrate
        working-directory: ./server
        run: python manage.py migrate
      - name: Test
        working-directory: ./server
        run: python manage.py test
